username: 'your email address'
password: 'your password'
phone_number:  'your phone number'

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'


positions:
- 'postion you want to apply'


locations:
- 'location'
- Remote

salary: 'expected salary'
rate: 25
# --------- Optional Parameters -------
uploads:
  Resume: 'definite path to your resume'
  Cover Letter: 'definite path to your cover letter'
  #Photo: # PATH TO photo


output_filename:
- out.csv

# blacklist:
# - # Company names you want to ignore

experience_level:
  # - 1 # Entry level
  # - 2 # Associate
  # - 3 # Mid-Senior level
  # - 4 # Director
  # - 5 # Executive
  # - 6 # Internship